import { UserApplication } from "./types";

export const mockUserApplications: UserApplication[] = [
  {
    id: "APP-1001",
    firstName: "Maria",
    lastName: "Lopez",
    email: "maria.lopez@example.com",
    phone: "512-555-1234",
    address: "1234 Cedar Ave",
    city: "Austin",
    zipCode: "78704",
    homeOwnershipStatus: "Owner",
    householdIncome: 55000,
    householdSize: 3,
    rebateProgramSelected: ["Home Electrification", "Weatherization"],
    applicationStatus: "Pending",
    submittedAt: "2025-06-21T14:32:00Z",
    documentsUploaded: ["proof_of_income.pdf"],
    assignedReviewer: "AdminUser1"
  },
  {
    id: "APP-1002",
    firstName: "James",
    lastName: "Smith",
    email: "james.smith@example.com",
    phone: "214-555-7890",
    address: "789 Oak Street",
    city: "Dallas",
    zipCode: "75201",
    homeOwnershipStatus: "Renter",
    householdIncome: 42000,
    householdSize: 2,
    rebateProgramSelected: ["Home Efficiency"],
    applicationStatus: "In Review",
    submittedAt: "2025-06-15T09:15:00Z",
    documentsUploaded: ["lease_agreement.pdf", "id_card.jpg"],
    assignedReviewer: "AdminUser2"
  },
  {
    id: "APP-1003",
    firstName: "Aisha",
    lastName: "Patel",
    email: "aisha.patel@example.com",
    phone: "713-555-4567",
    address: "456 Pine Blvd",
    city: "Houston",
    zipCode: "77002",
    homeOwnershipStatus: "Owner",
    householdIncome: 75000,
    householdSize: 4,
    rebateProgramSelected: ["Home Electrification"],
    applicationStatus: "Approved",
    submittedAt: "2025-05-30T16:45:00Z",
    documentsUploaded: [],
    assignedReviewer: "AdminUser1"
  },
  {
    id: "APP-1004",
    firstName: "Carlos",
    lastName: "Nguyen",
    email: "carlos.nguyen@example.com",
    phone: "210-555-9876",
    address: "987 Maple Dr",
    city: "San Antonio",
    zipCode: "78205",
    homeOwnershipStatus: "Renter",
    householdIncome: 38000,
    householdSize: 1,
    rebateProgramSelected: ["Weatherization"],
    applicationStatus: "Rejected",
    submittedAt: "2025-06-01T11:20:00Z",
    documentsUploaded: ["proof_of_income.pdf"],
    assignedReviewer: "AdminUser3"
  }
];
